# -*- coding: utf-8 -*-
"""Parser de archivos CSV de cotización generados por el cotizador EnviaTodo."""

import csv


# Índices de columnas en el CSV de cotización
_COL_ZONA = 0
_COL_PAQUETERIA = 4
_COL_SERVICIO = 5
_COL_CARGO_GUIA = 7
_COL_TOTAL = 11

_SIN_COBERTURA = "Sin cobertura"
_ZONA_MAP = {"A": "Zona A", "B": "Zona B", "C": "Zona C"}
_HEADER_PREFIX = "Zona"


def leer_cotizacion(ruta_csv: str) -> dict:
    """Parse a quotation CSV and return cheapest price per zone.

    Reads the cotizacion CSV files generated by the existing cotizador and
    returns the cheapest available service for each zone (A, B, C).

    Args:
        ruta_csv: Absolute or relative path to the quotation CSV file.

    Returns:
        dict: {
            'Zona A': {'precio_base': float, 'carrier': str, 'servicio': str},
            'Zona B': {'precio_base': float, 'carrier': str, 'servicio': str},
            'Zona C': {'precio_base': float, 'carrier': str, 'servicio': str},
        }

    Raises:
        FileNotFoundError: If the CSV file doesn't exist.
        ValueError: If no available services found for any zone.
    """
    try:
        f = open(ruta_csv, newline="", encoding="utf-8")
    except FileNotFoundError:
        raise FileNotFoundError("Archivo de cotización no encontrado: %s" % ruta_csv)

    # zona_letter -> list of (total_float, carrier, servicio)
    zona_rows: dict[str, list] = {}
    current_zona = None

    with f:
        reader = csv.reader(f)
        header_found = False

        for row in reader:
            if not row:
                continue

            # Detect header row
            if not header_found:
                if row[0].strip() == _HEADER_PREFIX:
                    header_found = True
                continue

            # Data rows
            zona_cell = row[0].strip()
            if zona_cell in _ZONA_MAP:
                current_zona = zona_cell
                if current_zona not in zona_rows:
                    zona_rows[current_zona] = []

            if current_zona is None:
                continue

            # Skip rows with no coverage
            if len(row) <= _COL_TOTAL:
                continue
            cargo_guia = (
                row[_COL_CARGO_GUIA].strip() if len(row) > _COL_CARGO_GUIA else ""
            )
            if cargo_guia == _SIN_COBERTURA:
                continue

            total_str = row[_COL_TOTAL].strip() if len(row) > _COL_TOTAL else ""
            if not total_str or total_str in ("—", "-", ""):
                continue

            try:
                total = float(total_str)
            except ValueError:
                continue

            carrier = row[_COL_PAQUETERIA].strip() if len(row) > _COL_PAQUETERIA else ""
            servicio = row[_COL_SERVICIO].strip() if len(row) > _COL_SERVICIO else ""
            zona_rows[current_zona].append((total, carrier, servicio))

    result = {}
    for letra, nombre_zona in _ZONA_MAP.items():
        servicios = zona_rows.get(letra, [])
        if not servicios:
            raise ValueError(
                "No se encontraron servicios disponibles para %s" % nombre_zona
            )
        mejor = min(servicios, key=lambda x: x[0])
        result[nombre_zona] = {
            "precio_base": mejor[0],
            "carrier": mejor[1],
            "servicio": mejor[2],
        }

    return result
